/**
 * <copyright>
 * Copyright (c) 2006 IBM Corporation.
 * All Rights Reserved.
 * </copyright>
 */
package com.ibm.semplore.search;

import com.ibm.semplore.xir.Term;

/**
 * SchemaQuery interface allows to specify querying over particular schema objects.
 * @author liu Qiaoling
 *
 */
public interface SchemaQuery extends Query {

	/**
	 * type of query over categories.
	 */
	public static final int TYPE_CATEGORY = 1;
	
	/**
	 * type of query over relations.
	 */
	public static final int TYPE_RELATION = 2;
	
	/**
	 * type of query over attributes.
	 */
	public static final int TYPE_ATTRIBUTE = 4;
    
    /**
     * Set the query type(over which schema objects to query), and the keywords of this query. The multiple words seperated by blank spaces are treated as disjunction.  
     * @param type
     * @param keywords 
     */
    public SchemaQuery set(int type, String keywords);
    
    /**
     * Returns the query type, over which schema objects to query.
     * @return
     */
    public int getType();

    
    /**
     * Returns the keywords of this query.
     * @return
     */
    public String getKeywords();
    
    /**
     * Returns the term of this query, generated by the query type and keywords.
     * @return
     */
    public Term getTerm();
    
}
